import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.targets.js.dsl.ExperimentalWasmDsl

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.ktlint)
}

// Captures the git hash and commit date at build time and writes them
// into a `BuildInfo` object the app can reference at runtime to
// identify which build a user is on. Same commit + clean tree ->
// byte-identical output; an uncommitted edit suffixes "-dirty" to the
// hash so it's obvious the build doesn't correspond to any pushed
// state. The output lives in `build/generated/buildInfo/` and is
// added to `commonMain` so every target picks it up.
val generateBuildInfo by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/buildInfo/commonMain")
    outputs.dir(outDir)

    val hash =
        providers.exec {
            commandLine("git", "rev-parse", "--short", "HEAD")
        }.standardOutput.asText.map { it.trim() }
    val dirty =
        providers.exec {
            commandLine("git", "status", "--porcelain")
        }.standardOutput.asText.map { if (it.isNotBlank()) "-dirty" else "" }
    val date =
        providers.exec {
            commandLine("git", "log", "-1", "--format=%cI", "HEAD")
        }.standardOutput.asText.map { it.trim() }

    inputs.property("hash", hash)
    inputs.property("dirty", dirty)
    inputs.property("date", date)

    doLast {
        val pkgDir = outDir.get().asFile.resolve("net/yonge_mallo/uqttt")
        pkgDir.mkdirs()
        pkgDir.resolve("BuildInfo.kt").writeText(
            """
            /*
             * Copyright 2026 David Yonge-Mallo
             *
             * Licensed under the Apache License, Version 2.0 (the "License");
             * you may not use this file except in compliance with the License.
             * You may obtain a copy of the License at
             *
             *     https://www.apache.org/licenses/LICENSE-2.0
             *
             * Unless required by applicable law or agreed to in writing, software
             * distributed under the License is distributed on an "AS IS" BASIS,
             * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
             * See the License for the specific language governing permissions and
             * limitations under the License.
             */

            package net.yonge_mallo.uqttt

            /** Build-time identifiers for the running binary. Generated by the
             * `generateBuildInfo` Gradle task; do not edit by hand. */
            object BuildInfo {
                const val GIT_HASH: String = "${hash.get()}${dirty.get()}"
                const val COMMIT_DATE: String = "${date.get()}"
            }

            """.trimIndent(),
        )
    }
}

kotlin {
    androidTarget {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    jvm("desktop") {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        moduleName = "composeApp"
        browser {
            commonWebpackConfig {
                outputFileName = "composeApp.js"
            }
        }
        binaries.executable()
    }

    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateBuildInfo)
            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.ui)
                implementation(compose.components.uiToolingPreview)
            }
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
        androidMain.dependencies {
            implementation(libs.androidx.activity.compose)
            implementation(compose.uiTooling)
        }
        val desktopMain by getting {
            dependencies {
                implementation(compose.desktop.currentOs)
            }
        }
    }
}

android {
    namespace = "net.yonge_mallo.uqttt"
    compileSdk = 35

    sourceSets["main"].manifest.srcFile("src/androidMain/AndroidManifest.xml")
    sourceSets["main"].res.srcDirs("src/androidMain/res")

    defaultConfig {
        applicationId = "net.yonge_mallo.uqttt"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "1.0.0"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
    }
}

compose.desktop {
    application {
        mainClass = "net.yonge_mallo.uqttt.MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Deb)
            packageName = "uqttt"
            packageVersion = "1.0.0"
        }
    }
}
